AICI VA FI O LISTA CU ZBORURI SI LOCURI RAMASE, IAR USERII VOR PUTEA APASA PE UN BUTON
LANGA SI SA CUMPERE BILETUL CARE VA TRIMITE O CERERE CATRE UN ALT UTILIZATOR CARE VERIFICA DACA MAI SUNT LOCURI
<a href="checkoutPage.php">Checkout Page</a>
<a href="home.php">Back to Home</a>